services:
  bot:
    image: ghcr.io/thatguyjustin/fatyoshi:main
    container_name: fatyoshi-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "BOT_TOKEN"
    volumes:
      - "${PWD}/config:/app/config"
      - "${PWD}/data:/app/data"